```{r}
# correlation plot
correlations <- cor(train)
corrplot(correlations, order = "hclust")

# pairs plot
pairs(~outcome + X1 + X2 + X3 + X4 + X5, data = train)
pairs(~outcome + X6 + X7 + X8 + X9 + X10, data = train)
pairs(~outcome + X11 + X12 + X13 + X14 + X15, data = train)
pairs(~outcome + X16 + X17 + X18 + X19 + X20 + X21, data = train)

# The dependent variable ("outcome") looks having decent linearity when plotting with other variables.  However, it is also obvious that some independent variables also have linear relationships with others.  The problem is multicollineaerity is obvious.

# The final descriptive analysis I used would be the relationship between "X21" and "outcome".
```

```{r}
p <- ggplot(train, aes(x = X21, y = outcome)) + geom_point() + geom_smooth()
p
```

```{r}
# identify and remove outliers
par(mfrow = c(1, 3))
boxplot(validation$outcome) # still have outliers
validation <- subset(validation,!(validation$outcome > quantile(validation$outcome, probs = c(.01, .995))[2]) | validation$outcome < quantile(validation$outcome, probs = c(.01, .995))[1])
boxplot(validation$outcome) # outliers were removed
```

```{r}
# remove outliers in variable "X21"
```
